apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-converter
  labels:
    app: currency-converter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: currency-converter
  template:
    metadata:
      labels:
        app: currency-converter
    spec:
      containers:
      - name: currency-converter
        image: rafaelmotac/currency_converter-0.0.1-snapshot:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: currency-converter-service
spec:
  selector:
    app: currency-converter
  ports:
    - protocol: TCP
      port: 31000
      targetPort: 8080
  type: LoadBalancer