---
spring:
  profiles:
    active: dev
  application:
    name: currency-converter-app
server:
  port: 8080
---
currency-converter:
  exchange-rates-api:
    url: "http://api.exchangeratesapi.io/v1/"
    access-key: "de594bec93e3f89b20c7bb1e81eb684f" # On a production application this should be stored in a secure place
  currencies:
    - AFN
    - ALL
    - DZD
    - USD
    - EUR
    - AOA
    - XCD
    - ARS
    - AMD
    - AWG
    - AUD
    - AZN
    - BSD
    - BHD
    - BDT
    - BBD
    - BYN
    - BZD
    - XOF
    - BMD
    - BTN
    - INR
    - BOB
    - BOV
    - BAM
    - BWP
    - NOK
    - BRL
    - BND
    - BGN
    - BIF
    - CVE
    - KHR
    - XAF
    - CAD
    - KYD
    - CLF
    - CLP
    - CNY
    - COP
    - COU
    - KMF
    - CDF
    - NZD
    - CRC
    - CUC
    - CUP
    - ANG
    - CZK
    - DKK
    - DJF
    - DOP
    - EGP
    - SVC
    - ERN
    - ETB
    - FKP
    - FJD
    - GMD
    - GEL
    - GHS
    - GIP
    - GTQ
    - GNF
    - GYD
    - HTG
    - HNL
    - HKD
    - HUF
    - ISK
    - IRR
    - IQD
    - ILS
    - JMD
    - JPY
    - JOD
    - KZT
    - KES
    - KPW
    - KRW
    - KWD
    - KGS
    - LAK
    - LBP
    - LSL
    - ZAR
    - LRD
    - LYD
    - CHF
    - MOP
    - MGA
    - MWK
    - MYR
    - MVR
    - MRU
    - MUR
    - XUA
    - MXN
    - MXV
    - MDL
    - MNT
    - MAD
    - MZN
    - MMK
    - NAD
    - NPR
    - NIO
    - NGN
    - OMR
    - PKR
    - PAB
    - PGK
    - PYG
    - PEN
    - PHP
    - PLN
    - QAR
    - MKD
    - RON
    - RUB
    - RWF
    - SHP
    - WST
    - STN
    - SAR
    - RSD
    - SCR
    - SLE
    - SGD
    - XSU
    - SBD
    - SOS
    - SSP
    - LKR
    - SDG
    - SRD
    - SZL
    - SEK
    - CHE
    - CHW
    - SYP
    - TWD
    - TJS
    - TZS
    - THB
    - TOP
    - TTD
    - TND
    - TRY
    - TMT
    - UGX
    - UAH
    - AED
    - GBP
    - USN
    - UYI
    - UYU
    - UZS
    - VUV
    - VEF
    - VED
    - VND
    - XPF
    - YER
    - ZMW
    - ZWL
